deadstar_item:
    name: "&b&lDead Star &7- &cRessurect &f%n"
    lore:
    - "&7Drop on a ground to"
    - "&7see the beauty of the nature."
    material: COAL_BLOCK

pull_blocks: true
pull_update_interval: 70 #in ticks

unaffected_blocks:
- "CHEST"
- "FURNACE"
- "TRAPPED_CHEST"
- "DROPPER"
- "SHULKER_BOX"
- "ENDER_CHEST"

unaffected_entities:
- "PLAYER"
- "WOLF"
- "OCELOT"
- "HORSE"

